# ~/.tmuxinator/Default.yml
# you can make as many tabs as you wish...

project_name: Default
project_root: ~/
tabs:
  - home:
      layout: main-vertical
      panes:
        -
        - src
        - clones
        - Dropbox
  - sohap:
      layout: main-vertical
      panes:
        - sohap
        - sohap && assets/backend
        - sohap && mongostart
  - sohap_mobile:
      layout: main-vertical
      panes:
        - sohapm
        - sohapm && www/socialhappen && serve
        - sohapm && coffee -cwb .
  - sohap_video:
      layout: main-vertical
      panes:
        - src && socialhappen-video
        - src && socialhappen-video
  - ec2:
      layout: main-vertical
      panes:
        - ec2 && sshbeta
        - ec2 && sshprod
  - planet:
      layout: main-vertical
      panes:
        - src && planet
        - src && planet
        - src && planet && coffee -cwb app/
  - dotfiles: dotfiles
