alias b=".."
alias cwd='pwd | pbcopy'
alias gowd='cd "`pbpaste`"'
alias mochacof='mocha --compilers coffee:coffee-script'
alias o.="open ."
alias o="open"
alias redo='sudo !!'
alias s.="subl -na ."
alias s="subl"
alias serve='python -m SimpleHTTPServer 8000'
alias v="vim"