alias b=".."
alias cwd='pwd | pbcopy'
alias fixappleeventsbug='sudo killall -KILL appleeventsd'
alias gowd='cd "`pbpaste`"'
alias ip='curl ifconfig.me'
alias jsc='/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc'
alias mochacof='mocha --compilers coffee:coffee-script'
alias mc='maid clean -n'
alias mcf='maid clean'
alias o.="open ."
alias o="open"
alias ox="open *.xcworkspace || open *.xcodeproj"
alias r="rails"
alias rc="rails console"
alias rg="rails generate"
alias rs="rails server"
alias rk="rake"
alias rkdm="rake db:migrate"
alias redo='sudo !!'
alias s.="subl -na ."
alias s="subl"
alias serve='python -m SimpleHTTPServer 8000'
alias v="vim"
