alias b=".."
alias cwd='pwd | pbcopy'
alias fixappleeventsbug='sudo killall -KILL appleeventsd'
alias gowd='cd "`pbpaste`"'
alias h='heroku'
alias ip='curl ifconfig.me'
alias jsc='/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc'
alias mochacof='mocha --compilers coffee:coffee-script'
alias mc='maid clean -n'
alias mcf='maid clean'
# alias mpc2mp3='2mp3 *.mpc'
alias nw="~/Applications/node-webkit.app/Contents/MacOS/node-webkit"
alias o.="open ."
alias o="open"
alias ox="open *.xcworkspace || open *.xcodeproj"
alias please='sudo bash -c "$(fc -l -1 | cut -d " " -f 4-)"'
alias r="rails"
alias rc="rails console"
alias rg="rails generate"
alias rs="rails server"
alias rk="rake"
alias rkdm="rake db:migrate"
alias redo='sudo !!'
alias s.="subl -na ."
alias sl="subl"
alias serve='python -m SimpleHTTPServer 8000'
alias v="vim"
